<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Nodes [

<!ENTITY % NameValue "CDATA">
<!ENTITY % PropType "(I|S|D|L|H|B)">
<!ENTITY % VersionValue "CDATA">

<!ELEMENT Prp (#PCDATA)>
<!ELEMENT Node (Node|Prp)*>
<!ELEMENT Nodes (Node)+>

<!ATTLIST Nodes version CDATA "1">

<!ATTLIST Node name CDATA #REQUIRED>

<!ATTLIST Prp name CDATA #REQUIRED>
<!ATTLIST Prp type CDATA #REQUIRED>
<!ATTLIST Prp value CDATA #REQUIRED>
]>
<Nodes version="1">
	<Node name="root">
		<Node name="classes">
			<Node name="class0">
				<Node name="fields"/>
				<Node name="methods"/>
				<Prp name="name" type="S" value="ClassDDT"/>
			</Node>
		</Node>
		<Node name="data">
			<Node name="group0">
				<Node name="fields">
					<Node name="field0">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Properties"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{DC60CD79-7C11-4FC6-A14A-A7427A80F3C1}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views1"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field1">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Output"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{3C034BED-26B6-4B1E-A6BB-83A33C842D86}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views2"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field2">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Strategy Navigator"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{494824C6-7F14-4963-8CB0-A0DAC75EDF15}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views3"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field3">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Tree Strategies"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{891EAF18-85C6-4974-A826-25E4605614CA}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views4"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field4">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Nodes Navigator"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{94253C91-BF5B-4344-B244-E624CB09E7E5}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views5"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field5">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Nodes Container"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{974850FF-6158-42DA-8BA3-19C42B8D15E4}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views6"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field6">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Debug: Strategy Variables"/>
									<Prp name="name" type="S" value="View"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="1"/>
									<Prp name="name" type="S" value="State"/>
									<Prp name="valuetype" type="I" value="5"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{9D380888-C527-44BE-8653-EDA763216BB5}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Default_views7"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
				</Node>
				<Node name="methods"/>
				<Prp name="checked" type="B" value="-1"/>
				<Prp name="name" type="S" value="Default_views"/>
			</Node>
			<Node name="group1">
				<Node name="fields">
					<Node name="field0">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="File"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="New Strategy"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{5D1644EB-476F-4FE1-BEE4-A0CF7E98C8FA}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu1"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field1">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="File"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Open Strategy..."/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{A0F2D0E7-9309-41C8-8026-2A5E734B5552}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu2"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field10">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="ViewEdit"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Copy"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{4EF5A55C-CC8A-4403-9A5B-B69AD93A61B4}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu11"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field11">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="ViewEdit"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Paste"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{558CDF8F-D71A-4BFF-9DC3-1E8EB45E9637}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu12"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field12">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="ViewEdit"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Find Node"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{DA7C83F0-BDB3-4D26-8D1E-968674AB697C}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu13"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field13">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="ViewEdit"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Zoom In"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{0B23ACFA-266A-4532-976F-28E72EE4EE0D}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu14"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field14">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="ViewEdit"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Zoom Out"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{033F31B7-2D52-496C-B9C1-1900CC25662E}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu15"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field15">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="ViewEdit"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Zoom"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{B1270FC1-0161-4CAC-97BB-FD95BAE88FCC}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu16"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field16">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Debug"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Full Run Debug Mode"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{1B03B614-E741-454E-AFD7-A7F6816F0D52}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu17"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field17">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Debug"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Step-By-Step Debug Mode"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{7002A67A-97BB-4D35-9B78-B4CA77A2FC2B}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu18"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field18">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Debug"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Stop Debug"/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{D1C32FDD-F802-4E53-A178-78E7AF0902D7}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu19"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field19">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Strategy"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Variables..."/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{5638889A-A83A-45A7-9F60-BEAAA13FE981}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu20"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field2">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="File"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Open Strategy Remote..."/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{F3FACF34-2A83-43E3-A477-222C482E73DE}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu3"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field20">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Strategy"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Constraints..."/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{36126445-1AC2-43FE-B368-D964A0B33C4A}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu21"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field21">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Strategy"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Global Script..."/>
									<Prp name="name" type="S" value="Text"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="PASS"/>
									<Prp name="name" type="S" value="ExpectedResult"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods"/>
							<Prp name="classref" type="S" value="ClassDDT"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="ClassDDT{E2230F11-8B48-41B2-A663-C151B059AC3C}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="BarMainMenu22"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
					<Node name="field22">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Strategy"/>
									<Prp name="name" type="S" value="Docker"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="Update Selected Nodes"/>